### ISSUE TITLE
[proposal] smartgateways.smartgateway.infra.watch/v1 CRD

### ISSUE THREAD

**Issue by leifmadsen** [infrawatch/smart-gateway-operator#81]
## Overview

The current CRD for the Smart Gateway is a bit of a rag-tag model that was mostly configured for the legacy Smart Gateway code, which only had 2 data stores; Prometheus and ElasticSearch. Originally only collectd was available as a transport, and then we added Ceilometer.

With the new sg-core + sg-bridge work, I believe we're starting to outgrow the existing `SmartGateway` CRD interface, and will continue to get more awkward as we implement additional transports, additional data store plugins, etc.

As of STF 1.3, the use of the legacy Smart Gateway is no longer required, and creation of `SmartGateway` objects will make sole use of sg-bridge + sg-core. A plugin system was added to sg-core for this release, migrates the majority of the existing functionality that legacy Smart Gateway provided, and adds new plugin capabilities, such as Loki as a data store for logging purposes.

It is possible additional plugins may be added over time, such as ability to support CloudEvents, and being able to handle them without many (or any) changes to the CRD would be nice from a release velocity perspective.

## Current Situation

The creation of `SmartGateway` objects is managed by the Service Telemetry Operator. We make use of 2 separate templates for the creation of Event and Metric SmartGateways. This can be seen here:

* https://github.com/infrawatch/service-telemetry-operator/blob/master/roles/servicetelemetry/templates/manifest_smartgateway_events.j2
* https://github.com/infrawatch/service-telemetry-operator/blob/master/roles/servicetelemetry/templates/manifest_smartgateway_metrics.j2

Each of these templates deals with collectd and ceilometer as data sources, and presumes Prometheus for metrics storage, and ElasticSearch for events storage.

Adding Loki as another data store, or logging data input as a new data source could require an additional template, or conditional expressions in the template. Over time this could get more difficult to read.

For reference, the old CRD (https://github.com/infrawatch/smart-gateway-operator/blob/master/deploy/crds/smartgateway.infra.watch_smartgateways_crd.yaml) contains various "plugin specific" configuration parameters. Additional configuration parameters would need to be added to support additional data inputs or data stores. The CRD is quite flat, and not all parameters are compatible with all data source types, or even required.

Looking at the CRD doesn't make it obvious which parameters are related to which data sources or data stores either.

## Proposal

Was going through the new sg-core (which is the only component we support as of STF 1.3, besides sg-bridge which is always paired with an sg-core deployment in the same pod), and wanted to propose a new CRD for future Smart Gateway Operator.

(Information about sg-core, the plugin types, and a sample configuration to start sg-core is available at https://github.com/infrawatch/sg-core/)

This ended up seeming simpler than I originally thought. We can actually abstract the configuration for the application and transport components it looks like without needing a strict API for those plugins. The expectation is that by having a loose configuration parameter for the various plugins, the CRD interface would not need to change much, if at all, to support additional transports or applications.

The advantage of this is that administrators could create their own plugins and still make use of the Smart Gateway Operator without needing to adjust the CRD for their plugin capabilities, or add additional templating or logic to the Operator. The administrator would simply create their own `sg-core` container image (possibly via the BuildConfig system of OpenShift, or published on quay.io) and refer to that new image for the particular `SmartGateway` object they need to create.

Configuration capabilities for the plugin would be passed in via the existing `application.config` or `transport.config` parameters.

### CRD

```yaml
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: smartgateways.smartgateway.infra.watch
spec:
  group: smartgateway.infra.watch
  names:
    kind: SmartGateway
    listKind: SmartGatewayList
    plural: smartgateways
    singular: smartgateway
    shortNames:
    - sg
  scope: Namespaced
  version: v1
  subresources:
    status: {}
  versions:
  - name: v1
    served: true
    storage: true
  validation:
    openAPIV3Schema:
      type: object
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://github.com/kubernetes/community/blob/master/contributors/devel/sig-architecture/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://github.com/kubernetes/community/blob/master/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          description: 'SmartGatewaySpec is a specification of the desired behavior
            of the Smartgateway deployment. More info: https://github.com/kubernetes/community/blob/master/contributors/devel/sig-architecture/api-conventions.md#spec-and-status'
          properties:
            pluginDir:
              description: Plugin directory path.
              type: string
            logLevel:
              description: Log level for sg-core.
              type: string
            transports:
              description: Transports to enable.
              items:
                properties:
                  name:
                    description: Name of the transport to load.
                    type: string
                  handlers:
                    type: array
                    style: simple
                    description: List of handler plugins to load for this transport.
                    items:
                      type: string
                  config:
                    description: Free form configuration for plugins.
                    type: string            
              type: array
            applications:
              description: Applications to load.
              items:
                properties:
                  name:
                    description: Name of the application.
                    type: string
                  config:
                    description: Free form configuration for the application.
              type: array
        status:
          description: Status results of an instance of Smart Gateway
          properties:
            conditions:
              description: The resulting conditions when a Smart Gateway is instantiated
              items:
                properties:
                  status:
                    type: string
                  type:
                    type: string
                  reason:
                    type: string
                  lastTransitionTime:
                    type: string
                type: object
              type: array
          type: object
```

### SmartGateway v1 object (example)

```yaml
apiVersion: smartgateway.infra.watch/v1
kind: SmartGateway
metadata:
  name: testing
spec:
  pluginDir: /plugins
  logLevel: INFO
  transports:
    - name: socket
      handlers:
        - collectd-metrics
      config: |
        address: /tmp/smartgateway
  application:
    - name: prometheus
      config: |
        host: localhost
        port: 8081
        withtimestamp: false
```

**Comment by leifmadsen** [comment]
CC: @pleimer @paramite @csibbitt

**Comment by leifmadsen** [comment]
Probably a couple more top level objects we'll want to add in there. For example, we'll want the `coreContainerImage` and `bridgeContainerImage` parameters so we can override or define the base images we want to load for that SmartGateway.

**Comment by csibbitt** [comment]
This LGTM, you basically re-implement the sg-core config in the CRD.

> Probably a couple more top level objects we'll want to add in there. For example, we'll want the `coreContainerImage` and `bridgeContainerImage` parameters so we can override or define the base images we want to load for that SmartGateway.

I reviewed all the old params and I think we also need  `size` (required for HA).

**Comment by leifmadsen** [comment]
> This LGTM, you basically re-implement the sg-core config in the CRD.
> 
> > Probably a couple more top level objects we'll want to add in there. For example, we'll want the `coreContainerImage` and `bridgeContainerImage` parameters so we can override or define the base images we want to load for that SmartGateway.
> 
> I reviewed all the old params and I think we also need `size` (required for HA).

Thanks. I will update the CRD sometime today with the missing parameters.

**Comment by pleimer** [comment]
This looks good to me, with the caveat that the Configuration for sg-core has changed slightly:

```yaml
apiVersion: smartgateway.infra.watch/v1
kind: SmartGateway
metadata:
  name: testing
spec:
  pluginDir: /plugins
  logLevel: INFO
  handleErrors: true/false #tell handlers to send errors to event bus
  transports:
    - name: socket
      handlers:
        name: collectd-metrics
        config: |
           # handler configs go here. They are not required by all handler plugins
      config: |
        address: /tmp/smartgateway
  application:
    - name: prometheus
      config: |
        host: localhost
        port: 8081
        withtimestamp: false
```
